version: '3.7'

services:
  app:
    build: ./api
    restart: always
    container_name: app
    command: python manage.py runserver 0.0.0.0:8000
    expose:
      - 8000
    links:
      - postgres:postgres
      - redis:redis
    env_file:
      - ./.env.dev
    volumes:
      - web-static:/usr/src/app/django_static
    
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    restart: always
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - web-static:/usr/src/app/django_static
      - ./nginx:/etc/nginx/conf.d
    links:
      - app:app
    depends_on: 
      - app

  postgres:
    image: postgres:12.0-alpine
    container_name: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/
  
  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    container_name: redis
    ports: 
      - "6379:6379"
    volumes: 
      - redisdata:/data
      
volumes:
  web-static:
  pgdata:
  redisdata:
